### ISSUE TITLE
TweenMax depricated

### ISSUE THREAD

**Issue by ductoanthanh** [zarocknz/javascript-winwheel#100]
GSAP 3 was released with many improvements, including TweenMax 

`this.tween = TweenMax.to(this, this.animation.duration, properties);`

can be changed to something like

`import gsap from "gsap";`
`this.tween = gsap.to(this, this.animation.duration, properties);`

just add gsap as your dependency

**Comment by zarocknz** [comment]
Thank you for brining this to my attention. I will look to update Winwheel.js to use the new gsap over the Christmas-new year break. Cheers.

**Comment by SturmB** [comment]
Apparently, this has not yet been implemented.

And there is no longer a download link for TweenMax (that I can find).

What can be done now for users who wish to use Winwheel? Are we just all out of luck?

**Comment by SturmB** [comment]
Never mind. It seems Winwheel will work (say that 3 times fast) even if using the latest version of GSAP 3. I guess they still have the old TweenMax code in it?

Still, in case it _does_ get removed in the future, it would probably be a good idea to go ahead and update Winwheel to take advantage of the newer implementation of TweenMax in GSAP 3.
