### ISSUE TITLE
Option to "align" text like curved but displayed straight

### ISSUE THREAD

**Issue by jmluy** [zarocknz/javascript-winwheel#103]
Is there an option to display text horizontally but similar to "curved"'s alignment?

**Comment by zarocknz** [comment]
Hi, no there is currently no option for this and I don't see how any combination of the existing parameters could make this happen.

**Comment by jmluy** [comment]
@zarocknz thanks for confirming.

**Comment by ekiselyov** [comment]
Same issue. And problem with curved – only monospaced fons looks good on curve. Any other fonts looks ugly.
