### ISSUE TITLE
More flexible text

### ISSUE THREAD

**Issue by IgnacioGaldames** [zarocknz/javascript-winwheel#11]
It would be great to have html tags or at least text overflown to two lines.

**Comment by beetjerky** [comment]
Thanks for this awesome tool, dude!! This is also what I came here to request. It'd be nice to be able to put some subtext under the text (preferably via html). If you could suggest even a temporary hack, that'd be great. I noticed if I change the 2 to 1.5 below, it will make some room to put text under, but I have no idea how to get it there.

`var textAngle = this.degToRad(seg.endAngle - ((seg.endAngle - seg.startAngle) / 2) + this.rotationAngle - 90);
`

For example, I'm trying to draw segment text horizontally to look like the following, with the second line in smaller text, ideally.

North Dakota
(Bismarck)

By the way, I've tried a lot of different wheels, and yours is the best. Lots of options, and being able to predict the stopping point is awesome.

Thanks again!

**Comment by zarocknz** [comment]
Thanks for the feedback. 

I looked in to this the other day and its not going to be easy, especially if the second line can have different size or styling to the first. @beetjerky I would suggest using an image for the wheel if that is possible, see http://dougtesting.net/winwheel/docs/tut9_creating_with_an_image as that will give you full control over the visuals of the wheel.

HTML canvas text does not accept or use HTML markup, only plain text. The text attributes are controlled by font size, family and the fillStyle and strokeStyle, with the text itself rendered by stoking and filling.

If all the lines of text can have the same color and formatting the simplest solution would be to break the text on \n and then loop and output adjusting the position vertically to position the second line below the first in the drawText() function. If each line can be different then I was possibly thinking of an array/object for the 'text' property with a label attribute and all the font and colour options attributes of the text object as well. However I want to be careful not to over-complicate the wheel or segment parameters for everyday use.

Multi-line text does seem to open a can of worms, so to speak, also in terms of positioning in the segments of the wheel - for example I imagine it would be logical for when there is 3 lines to have the second one at the halfway point of the segment and then the other 2 sitting either side of it. Might need a textVerticalAlign property, for example, to control if the text sits at the top, bottom, or middle of the segment (when talking about normal horizontal text).

I'll think on it some more and probably have another play around over the Christmas holidays. Please feel welcome to add any of your own thoughts or suggestions on how this might work to this ticket.

Cheers,
DouG.

**Comment by beetjerky** [comment]
Thanks for responding. Sorry, I've been busy during the holidays. This added feature is AWESOME! Thanks. Also, not a big deal and just a personal preference thing, but some people (like me) find it easier t o use the literal '\n' as a delimiter instead of an actual new line, especially in the case of a title/subTitle. So, I "hacked" lines 798-799 to escape the backslash.

`// Split the text into multiple lines using new lines or the literal '\n' character.
 var lines = seg.text.split(/\\n|\n/); `

I'll send you a link later to where I'm including your wheel in my project (assuming I can finish it in this lifetime).

Thanks again!

**Comment by beetjerky** [comment]
Sorry. My suggestion was dumb. My string with the \n just needed to be in double quotes instead of single quotes and your way works fine.
