### ISSUE TITLE
Can you please add version 2.8.0 to jsdelivr?

### ISSUE THREAD

**Issue by tinodo** [zarocknz/javascript-winwheel#112]
As a convenience, can you please update jsdelivr to you 2.8.0 version?
I am referencing this: https://www.jsdelivr.com/package/npm/winwheeljs

It would be really, really cool if you also could use SRI the file, such that we can validate the integrity of the file(s).

This would be great!!!

(I also see you own https://www.jsdelivr.com/package/npm/winwheel, but that's really old.)

**Comment by jimaek** [comment]
You can use the Github files directly too https://cdn.jsdelivr.net/gh/zarocknz/javascript-winwheel@2.8.0/Winwheel.min.js

**Comment by tinodo** [comment]
Thanks! Will do that!
