### ISSUE TITLE
Setting the Prize to be won before spinning

### ISSUE THREAD

**Issue by jCrip** [zarocknz/javascript-winwheel#12]
Hi, first of all I want to thank you for your work, is really great, the documentation is fantastic!
Now, I created a wheel and set the pointerAngle equal to 90 to put it on the right side of the wheel, I use the pointerGuide helper to check it and everythings is ok.
The issue comes when i set an stopAngle using the getRandomForSegment() this stop the wheel in the segment i want but pointing to the top, so the getIndicatedSegment() shows me an incorrect information and the pointer is pointing the incorrect segment.
I've read all the documentation to check if there's an option to set the final direction of the selected segment to be at the same direction of the pointerAngle and I couldn't find a solution. Maybe I miss something.

If you can help me with this I would appreciate it greatly.

Thank you

**Comment by jCrip** [comment]
Example: 

``` js
var theWheel = new Winwheel( {
  'canvasId': 'my-roulette',
  'fillStyle': '#e7706f',
  'lineWidth': 3,
  'textAlignment': 'outer',
  'pointerAngle': 90,
  'numSegments': 16,
  'segments': [
    {'fillStyle' : '#eae56f', 'text' : 'Segment 1'},
    {'fillStyle' : '#89f26e', 'text' : 'Segment 2'},
    {'fillStyle' : '#7de6ef', 'text' : 'Segment 3'},
    {'fillStyle' : '#e7706f', 'text' : 'Segment 4'},
    {'fillStyle' : '#eae56f', 'text' : 'Segment 5'},
    {'fillStyle' : '#89f26e', 'text' : 'Segment 6'},
    {'fillStyle' : '#7de6ef', 'text' : 'Segment 7'},
    {'fillStyle' : '#e7706f', 'text' : 'Segment 8'},
    {'fillStyle' : '#eae56f', 'text' : 'Segment 9'},
    {'fillStyle' : '#89f26e', 'text' : 'Segment 10'},
    {'fillStyle' : '#7de6ef', 'text' : 'Segment 11'},
    {'fillStyle' : '#e7706f', 'text' : 'Segment 12'},
    {'fillStyle' : '#eae56f', 'text' : 'Segment 13'},
    {'fillStyle' : '#89f26e', 'text' : 'Segment 14'},
    {'fillStyle' : '#7de6ef', 'text' : 'Segment 15'},
    {'fillStyle' : '#e7706f', 'text' : 'Segment 16'}
  ],
  'pointerGuide' : 
          {
              'display'     : true,
              'strokeStyle' : 'red',
              'lineWidth'   : 3
          },
  'animation': 
  {
    'type': 'spinToStop',
    'duration': 2,
    'spins': 12, 
    'easing': 'Expo.easeOut',
    'callbackFinished': 'alertPrize()'
  }
} );

function alertPrize() {
  var winningSegment = theWheel.getIndicatedSegment();
  console.log('The Winning segment is: ' + winningSegment.text);

  var winningSegmentNumber = theWheel.getIndicatedSegmentNumber();
  console.log(winningSegmentNumber)
}

// Function with formula to work out stopAngle before spinning animation.
function calculatePrize() {
  var segmentNumber = '4';
  var stopAt = theWheel.getRandomForSegment(segmentNumber);
  theWheel.animation.stopAngle = stopAt;
  theWheel.startAnimation();
}
```

Wheen this wheel spin the segment 4 is pointing at the top but the pointer is at the right, and the console show the info of the info of the segment 8

**Comment by zarocknz** [comment]
Hi @jCrip, sorry this was my fault; i forgot to include the pointerAngle in the calculations when the stopAngle is set. Just fixed this so if you grab the Winwheel.js file from the master branch your wheel should work as expected now.

Thanks for reporting this!

Cheers,
DouG.
