### ISSUE TITLE
Winwheel in angular 2 app

### ISSUE THREAD

**Issue by theunreal** [zarocknz/javascript-winwheel#17]
How I can import winwheel to an angular 2 app?

**Comment by zarocknz** [comment]
Hi. 

I'm not sure exactly as I have no experience with angular. I suppose you just import it like any other plain old js file. There must be a tutorial out there somewhere for that.

I have no idea if this works, and its a little out of date, but perhaps look at this fork of the module which was done so it could be used inside angular https://github.com/ipengyo/angular-winwheel.

Regards,
DouG.
