### ISSUE TITLE
Highlight When Spin is Finish

### ISSUE THREAD

**Issue by hibuno** [zarocknz/javascript-winwheel#35]
Hi @zarocknz ,

Can i highlight area of winner segment? Or does plugin have function / option to show where a winner segment?

Maybe like this picture :

![screen shot 2017-12-28 at 10 53 01](https://user-images.githubusercontent.com/17744043/34399769-53b13bf0-ebbd-11e7-8a7b-f245678dce37.png)

I want WinWheel highlight winner segment to notify the user. 

Thank you 😃

**Comment by zarocknz** [comment]
Hi @muhibbudins  yes this is possible. 

Please see this tutorial http://dougtesting.net/winwheel/docs/tut13_prize_detection the last example on the page "Changing the colour of the winning segment" does this.

When the spinning stops you can change the colour of the segment and then re-draw the wheel to show the changes as seen on line 55 and 58 of the code listing on that tutorial page.

Kind regards,
DouG.

**Comment by hibuno** [comment]
Sound good!

But wait, i use image for segment. So how to change it? Cz code from the tutorial not working for me 😄 

This is my code : 
```javascript
window.wheelCallback = function() {
    // Get the number of the winning segment.
    var winningSegmentNumber = theWheel.getIndicatedSegmentNumber();
 
    // Loop and set fillStyle of all segments to gray.
    for (var x = 1; x < theWheel.segments.length; x ++) {
        theWheel.segments[x].fillStyle = 'https://orori-telin.akamaized.net/assets.orori.com/indonesia/img/promo/wheel-of-fortune/pie20.png';
    }
 
    // Make the winning one yellow.
    theWheel.segments[winningSegmentNumber].fillStyle = 'https://orori-telin.akamaized.net/assets.orori.com/indonesia/img/promo/wheel-of-fortune/pie25.png';
 
    // Call draw function to render changes.
    theWheel.draw();

    $('.spinning_voucher').addClass('active');
}
```

**Comment by zarocknz** [comment]
Ah yes, sorry for segment images you will need to do slightly different. You can change the image used for the segment in the function called after the animation like this...

```
function alertPrize()
{
    // Change the image of the indicated segment so we can better inform the user of winning.
    var winningSegmentNumber = theWheel.getIndicatedSegmentNumber();
    theWheel.segments[winningSegmentNumber].changeImage("win.png");
}
```

The key part is using the changeImage() function to change the image for the segment(s).

Hope this helps.

**Comment by hibuno** [comment]
Nice dude! Its work. Thanks @zarocknz 👍
