### ISSUE TITLE
Stop wheel on already known prize number

### ISSUE THREAD

**Issue by codeezy** [zarocknz/javascript-winwheel#36]
How i can stop wheel on prize number what was generated from other var or server side?
example i want stopped on segment: Prize 1.
Thanks.

**Comment by zarocknz** [comment]
Hi @codeezy. There are a couple of ways to do this as detailed on this tutorial page: http://dougtesting.net/winwheel/docs/tut14_setting_the_prize

The key part is setting the Winwheel.animation.stopAngle to an angle inside the segment you want to be displayed when the spinning stops.

Cheers,
DouG.
