### ISSUE TITLE
how to make pins responsive? 

### ISSUE THREAD

**Issue by nog123** [zarocknz/javascript-winwheel#38]
any ideas?  I got the wheel responsive by using bootstrap, and a call to the resizeCanvas() function supplied by one of the commenters - but getting the pins to scale seems to be beyond me. 
any help appreciated.
thanks

**Comment by zarocknz** [comment]
@nog123 sorry I am not familiar with bootstrap. Can you clarify what resizeCanvas() function and what commenter you are referring to?

Pins have an outerRadius and some other properties which could be adjusted in a resize function. Please take a look at http://dougtesting.net/winwheel/refs/class_pin if you have not done so already.

Note: I am slowly working on responsive features for Winwheel.js and hope to have something ready in a few months for this.
