### ISSUE TITLE
one image = one sector

### ISSUE THREAD

**Issue by berezmax** [zarocknz/javascript-winwheel#4]
Is it possible to put one image on each sector?

**Comment by zarocknz** [comment]
Hi,

Not at this time. It's something that I thought of a while back which would be cool, but no one has asked for it before so its down the bottom of my possible features list.

**Comment by berezmax** [comment]
ok, not at this time )

**Comment by zarocknz** [comment]
Another person has asked for this feature so I need to give some priority.

**Comment by zarocknz** [comment]
This feature has been implemented in release 2.4
