### ISSUE TITLE
Predetermined Winning & Segments Images

### ISSUE THREAD

**Issue by brandy** [zarocknz/javascript-winwheel#40]
This plugin looks awesome but I have a few questions that I can't seem to figure out.

1. I'd like to use PHP to predetermine a winning segment, then have the wheel spin randomly and land on that winner. Would this be possible with this plugin?

2. I'd like to show little thumbnails of images instead of segment names. Would this be possible as well?

Thanks for the help :octopus:

**Comment by zarocknz** [comment]
Hi @brandy, 

Yes the first thing is most definitely possible, please see this tutorial page http://dougtesting.net/winwheel/docs/tut14_setting_the_prize "Calling server-side script to calculate prize won" section about half way down.

As for the second thing, there is nothing currently built in to Winwheel.js to do that, should be possible with either a modification to the draw() function to also call a function to draw some icons, or possibly some code in the page itself which hooks in to the animation callback.
