### ISSUE TITLE
The lineWidth doesn't seem to be working

### ISSUE THREAD

**Issue by DogAndHerDude** [zarocknz/javascript-winwheel#42]
It's either `on` or `off`

`
          canvasId: 'lumifish-wheel', 
          numSegments: 24, 
          outerRadius: outerRadius, 
          innerRadius: innerRadius, 
          textFontFamily: '\'Roboto\', sans-serif', 
          textFontSize: 22, 
          textFontWeight: '900', 
          textAlignment: 'outer', 
          fillStyle: '#fff', 
          textFillStyle: '#fff', 
          lineWidth: 15, // ain't doing nothin' 
`

Now what's up with that?

Secondly, why can't I have just an outline around the wheel, but ignore the inner outline for the segments?

I kinda need the pins to be sitting out on the white outline around the wheel.

**Comment by zarocknz** [comment]
Hi @TheImpressionist 

1) lineWidth is working as expected for me; copying and pasting your config in to the code of the basic code wheel example I see thick (15px) lines in between all the segments. I used the latest copy of Winwheel.js in the master branch for this, though I don't recall it being broken in earlier releases.

2) The line width applies to all sides of a shape when drawn on HTML canvas. The wheel is created out of individual segments which begin at the center point, go to the outside, arc around, then back in to the center point. Think of each segment like the slice of a pizza and the wheel simply a number of slices next to each other to make a whole circle / whole pizza.

If you would like a thicker outline around the outside of the wheel then consider using a background image http://dougtesting.net/winwheel/docs/tut10_pointers_and_backgrounds behind the wheel and make the outerRadius of the wheel smaller than the circle of the background.

3) use a negative margin for the pins to push them outside of the wheel and on to the blank canvas. You may need to reduce the outerRadius of the wheel so all the pins can be seen. If you have not done so already I would suggest reading this tutorial on pins and their options: http://dougtesting.net/winwheel/docs/tut18_displaying_pins

Regards,
DouG
