### ISSUE TITLE
Rotate 2 part wheels in opposite directions

### ISSUE THREAD

**Issue by Krystille** [zarocknz/javascript-winwheel#43]
Is it possible to rotate the outer wheel in clockwise direction while inner wheel into anti-clockwise direction? If yes, how? Thanks

**Comment by zarocknz** [comment]
Hi @GK1995. Yes this should be possible, rather than setting

`innerWheel.rotationAngle = outerWheel.rotationAngle;`

try

`innerWheel.rotationAngle = (0 - outerWheel.rotationAngle);`

Anti-clockwise rotation is simply giving the rotation angle a negative value so that should work. Let me know!

**Comment by Krystille** [comment]
It works! Thanks
