### ISSUE TITLE
Responsive 2 part wheel 

### ISSUE THREAD

**Issue by Krystille** [zarocknz/javascript-winwheel#44]
May I know how to make the 2 part wheel responsive together with the wheel background? I tried one of the suggestion on last issues but the inner wheel doesn't display when resizing, only theouter wheel is displayed. Thanks in advance.

**Comment by zarocknz** [comment]
Hi @GK1995 below is the code I used for the resize function to work as expected, the key thing is calling draw() for both the wheels and ensuring that false is passed to one of those draw calls so the canvas is not cleared which would make the other wheel disappear...

    function resizeCanvas()
    {
        // Get the canvas
        var canvas = document.getElementById('canvas');

        // Get width of window.
        var w = window.innerWidth;

        // Set height to the current height of the canvas since we don't adjust it.
        var h = canvas.height;

        // Assuming only the width will change to be responsive.
        canvas.width = w;

        // To ensure the wheel stays inside the canvas, work out what is the smaller
        // value between width and height, and set the outerRadius to half of that.
        if (w < h) {
            outerWheel.outerRadius = (w / 2);
        } else {
            outerWheel.outerRadius = (h / 2);
        }

        // Make the inner radius half that of the outer radius. The inner radius also is
        // the outer radius of the inner wheel.
        outerWheel.innerRadius = (outerWheel.outerRadius / 2);
        innerWheel.outerRadius = outerWheel.innerRadius;

        // In order to keep the wheel in the center of the canvas the centerX and
        // centerY need to be set to the middle point of the canvas.
        outerWheel.centerX = (canvas.width / 2);
        outerWheel.centerY = (canvas.height / 2);

        // Match center of the inner wheel to that of the outer wheel.
        innerWheel.centerX = outerWheel.centerX;
        innerWheel.centerY = outerWheel.centerY;

        // Other possible @TODO
        // - Alter the font sizes

        // Re-draw both wheels passing false to the draw of the inner wheel
        // so the canvas is not cleared (removing the outer wheel).
        outerWheel.draw();
        innerWheel.draw(false);
    }

I'm now about to see if I can figure out how to make the wheel background responsive.

**Comment by zarocknz** [comment]
OK, so I seem to have figured it out, change the css for the_wheel to like below - the 100% width and no repeat of the image...

```
td.the_wheel
{
    background-image: url(./wheel_back.png);
    background-position: center;
    background-repeat: no-repeat;
    background-size: 100% auto;
}
```
Then make the following changes in the resize function JS, cutting the canvas.width = w line and putting it below where the outer radius is set as seen here...

```
if (w < h) {
    outerWheel.outerRadius = (w / 2) - 10;  // The -10 Allows part of the background to show creating a thicker border around the outside
} else {
    outerWheel.outerRadius = (h / 2) - 10;
}

// Set the width of the canvas to slightly larger than the wheel. This ensures the background does not become very large.
canvas.width = (outerWheel.outerRadius * 2) + 10;
```
Adjust the value 10 in the code above as desired to make the border around the outside of the wheel thicker or thinner. The larger the radius of the wheel the less the background will show so the line around the edge of the circle will appear thinner.

Hope this helps.
DouG.
