### ISSUE TITLE
Can we stop the wheel at a segment where we want

### ISSUE THREAD

**Issue by waleedpl** [zarocknz/javascript-winwheel#55]
Actually i am using this wheel for a lottery event
so i want to stop the wheel on a specific segment where i want is that possible ?

**Comment by zarocknz** [comment]
Yes there is an entire tutorial on that. Please read http://dougtesting.net/winwheel/docs/tut14_setting_the_prize

**Comment by EliezerB123** [comment]
To be more clear, a function for this already exists. (The documentation is somewhat unclear.)

The correct method for stopping on prize #3 is this:

                var stopAt = myWheel.getRandomForSegment(3);
                myWheel.animation.stopAngle = stopAt;
                myWheel.startAnimation();
