### ISSUE TITLE
Reverse rotation problem

### ISSUE THREAD

**Issue by sanikamal** [zarocknz/javascript-winwheel#59]
var firstWheel=new Winwheel({
            'canvasId'    		: 'firstcanvas',
            'outerRadius'		: 170,
            'numSegments' 		: 10,
            'innerRadius' 		: 5,
            'textFontSize'		: 55,
            'textOrientation'	: 'vertical',
            'textFontFamily'	: 'Courier',
            'textAlignment'		: 'outer',
            'textFillStyle'		:'#ffffff',
            'strokeStyle'		:'#ffff00',
            'textMargin'		: 5,
            'segments'    		:
                [
                    {'fillStyle' : '#ff0000', 'text' : '1'},
                    {'fillStyle' : '#000000', 'text' : '2'},
                    {'fillStyle' : '#ff0000', 'text' : '3'},
                    {'fillStyle' : '#000000', 'text' : '4'},
                    {'fillStyle' : '#ff0000', 'text' : '5'},
                    {'fillStyle' : '#000000', 'text' : '6'},
                    {'fillStyle' : '#ff0000', 'text' : '7'},
                    {'fillStyle' : '#000000', 'text' : '8'},
                    {'fillStyle' : '#ff0000', 'text' : '9'}
                ],
            'lineWidth'   		: 3,
            'animation' 		:           
                    {
                        'type'     : 'spinToStop',  
                        'duration' : 45,             
                        'spins'    : 60,
                'callbackFinished' :'calculatePrizeOnServer1()',             
                     'callbackAfter' : 'drawTriangle()',
                     'callbackSound' : 'playSound2()',
                     'soundTrigger'  : 'pin'
                        },
                        'pins' :
                        {
                            'number' : 20,
                            'outerRadius' : 5,
                            'margin'      : 5,
                            'fillStyle'   : '#00ff00',
                            'strokeStyle' : '#ffffff'
                        }
			});
		var xhr1 = new XMLHttpRequest();
		xhr1.onreadystatechange = ajaxStateChange1;
        function calculatePrizeOnServer1(){
            xhr1.open('GET',"calculate_price_first_digit.php", true);
            xhr1.send('');
        }
        function ajaxStateChange1(){
            if (xhr1.readyState < 4){
                return;
            }
     
            if (xhr1.status !== 200){
                return;
            }
     
            if (xhr1.readyState === 4){
                var segmentNumber1 = xhr1.responseText;
//                 segmentNumber1=4;
				first_digit=segmentNumber1;
     
                if (segmentNumber1){
                	segmentNumber1=parseInt(segmentNumber1);
                   var stopAt1 = firstWheel.getRandomForSegment(segmentNumber1);
                   firstWheel.animation.stopAngle = stopAt1;
                   firstWheel.startAnimation();
//                    highlight_segment(firstWheel,segmentNumber1);
                }
                else{
                   var stopAt1 = firstWheel.getRandomForSegment(10);
                   firstWheel.animation.stopAngle = stopAt1;
                   firstWheel.startAnimation();
//                    highlight_segment(firstWheel,10);

                }
            }
        }
     
		drawTriangle();
		function drawTriangle(){
            var ctx = firstWheel.ctx;
            ctx.strokeStyle = 'navy';    
            ctx.fillStyle   = 'aqua';     
            ctx.lineWidth   = 2;
            ctx.beginPath();             
            ctx.moveTo(190, 10);
            ctx.lineTo(190, 70);
            ctx.lineTo(200, 90);
            ctx.lineTo(210, 70);
            ctx.lineTo(210, 10);
            ctx.lineTo(190, 10);
            ctx.stroke();
            ctx.fill();
        }
		var audio2 = new Audio('sound/Tick.mp3');

        function playSound2(){
//             audio2.pause();
            audio2.currentTime = 0;
            audio2.play();
        }

the wheel reverse rotated. how to fix this problem. I need to spin only one direction and stop in the defined result segment. It stops in the correct segment but for finding segment it rotates reverse.

**Comment by zarocknz** [comment]
Try resetting the wheel's rotation angle before starting the animation.  

```
firstWheel.RotationAngle = 0;
firstWheel.startAnimation();
```

**Comment by sanikamal** [comment]
Thank U. Finally problem solved.
