### ISSUE TITLE
Issue with the segments of the wheel becomes overlapped when more segments are added

### ISSUE THREAD

**Issue by hannahhaidi** [zarocknz/javascript-winwheel#65]
<?php
$config=parse_ini_file(__DIR__."/../bragconfig.ini");

if(!isset($_SESSION)) 
{ 
  session_name($config['sessionName']);
  session_start(); 
}
if(!isset($_SESSION["colorCode"])){
    $_SESSION["colorCode"]=array();
}
//$_SESSION["colorCode"]=array();
require("../phpfunctions/users.php");

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <script type="text/javascript" src="../js/jquery-3.3.1.min.js"></script>
    <script src="../js/bootstrap.min.js" ></script>

    
    
    <link rel="stylesheet" href="../js/plusminusbutton/style.css" />
    <script src="../js/plusminusbutton/script.js"></script>

    
    <script src="../js/javascript-winwheel-2.7.0/Winwheel.js" ></script>
    <script src="../js/javascript-winwheel-2.7.0/TweenMax.min.js"></script>

    
    <link href="../css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="../js/bootstrap-toggle.min.js"></script>

    
    <link rel="stylesheet" href="../css/dataTables.bootstrap4.min.css">
    <script src="../js/jquery.dataTables.min.js" ></script>
    <script src="../js/dataTables.bootstrap4.min.js" ></script>
    <script src="../js/dom-text.js" ></script>

    <style>
        
    
        hr {
            margin-top: 1rem;
            margin-bottom: 1rem;
            border: 0;
            border-top: 2px solid rgba(0, 0, 0, 0.1);
        }
   
 #canvasContainer {
     position: relative;
     width: 300px;
     height:0;
 }
  
 #canvas {
     z-index: 1;
 }
  
 #prizePointer {
     
     position: absolute;
     left: 175px;
     top: -12px;
     z-index: 999;
 }
 #wheelSpinner {
 
 
    position: absolute;
    left: 150px;
    top: 150px;
    cursor:pointer;
    background-color:#DAA520
 }
 #wheelSpinner{
    display: inline-block;
    text-decoration: none;
    background: gold;
    color: #FFF;
    font-size:3em;
    width: 120px;
    height: 120px;
    line-height: 120px;
    border-radius: 50%;
    text-align: center;
    font-weight: bold;
    vertical-align: middle;
    overflow: hidden;
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.29);
    border-bottom: solid 3px #bd6565;
    transition: .4s;
}

#wheelSpinner:active{
    -ms-transform: translateY(2px);
    -webkit-transform: translateY(2px);
    transform: translateY(2px);
    box-shadow: 0 0 1px rgba(0, 0, 0, 0.15);
    border-bottom: none;
}

#center {
  position: absolute;
 
  z-index: 15;
  top: 50%;
  left: 50%;
  margin: -100px 0 0 -150px;
}
@media screen and (max-width: 600px) {
    table.winner_list{ 
        display:none;
    
    }
    table.winner_list{
        background:gold;
        position:fixed;
        z-index:999;
    }
    table.winner_list td{
        border-top:1px solid black;
    }
 
}

@media only screen and (min-width:600px) {
    .hide-on-desktop{
        display: none;
        
    }
}

    .show_toggle:active table.winner_list{
        display:block;
    }

    .show_toggle:active .hide-on-desktop{
        display:none;
    }

table.winner_list{
    
}
table.winner_list  thead> tr >th{
    background:gold;
    color:black;
    padding:20px;
    letter-spacing: 3px;
}
table.winner_list tbody td {
    border-bottom:2px solid gold;
    color:green;
    text-transform:uppercase;
    font-style: oblique;
    text-align:center;

}
body{
    background: #d9a7c7;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #fffcdc, #d9a7c7);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #fffcdc, #d9a7c7); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
         

}

</style>
<script>
    $(document).ready(function() {
        
        var theWheel=null;
        var dataZ=null;
            var table = $('#referalUserListTable').DataTable( {
                "columnDefs": [
                    {
                        "targets": [3],
                        "orderDataType": "dom-text"
                    
                    },{
                        "targets": [0],
                        "orderable": false
                    }
                ]
            } );

        updateWheel();
        updateWinnerList();
         $('.modal').on('hidden.bs.modal', function () {
            // location.reload();
            updateWheel();
            updateWinnerList();
        })

        

    } );

    function updateReferalTableWinner(userId_){
        
        $.ajax({
            type  : 'GET',
            url  : '../phpfunctions/luckydraw.php?',
            data : {updateReferalTableWinner:'true',userId:userId_},
            success: function (data) {
                
            },
            error: function(xhr, status, error) {
                console.log(error);
                
            }
        });
    }

    function updateReferalTable(userId_,str){
       
       var qty_=str.value;
       if(qty_>0)
        $.ajax({
            type  : 'GET',
            url  : '../phpfunctions/luckydraw.php?',
            data : {updateReferalTable:'true',userId:userId_,qty:qty_},
            success: function (data) {
                console.log(data);
                
            },
            error: function(xhr, status, error) {
                console.log(error);
                
            }
        });
       
    }

    function updateWheel(){
        $.ajax({
            type  : 'GET',
            url  : '../phpfunctions/luckydraw.php?',
            data : {getEligleUserForContest:'true'},
            success: function (data) {
                //console.log(data);
                if(data!='null' ){
                    data=JSON.parse(data);
                 //   console.log(data);
                    var qty=data.length;
                    createWheel(data);
                }
                
            },
            error: function(xhr, status, error) {
                console.log(error);
                
            }
        });
    }

    function updateWinnerList(){
        $.ajax({
            type  : 'GET',
            url  : '../phpfunctions/luckydraw.php?',
            data : {getWinnerList:'true'},
            success: function (data) {
                
                if(data!=null){
                    
                    data=JSON.parse(data);
                    
                    $("table.winner_list tbody").empty();
                    var dataRow="";
                    $.each(data, function(index, obj){
                       
                        dataRow+="<tr><td>"+obj.shortName+" ("+obj.memberId+")</td></tr>";
                    });
                   
                    $("table.winner_list tbody").html(dataRow);
                }
                
            },
            error: function(xhr, status, error) {
                console.log(error);
                
            }
        });
    }

</script>
</head>
<body>
<?php 
  include $_SERVER['DOCUMENT_ROOT']."/brag/navMenu.php";
?>

<h1 class="display-4">LUCKY DRAW CONTEST 
    <button type="button" class="btn btn-info"  data-toggle="modal" data-target="#referalUserListModal">
        REFERAL
    </button>
</h1>

<hr/>

<div class="container" >
    <div id="center">
        <div id="canvasContainer"  >
            <canvas id="canvas" width="404" height="404" >
                <p style="{color: white}" align="center">Sorry, your browser doesn't support canvas. Please try another.</p>
            </canvas>
            <a id="wheelSpinner" href="#" onClick="startSpin();"  >SPIN</a>

            <img id="prizePointer" src="../js/javascript-winwheel-2.7.0/resources/basic_pointer.png" alt="V" />
        </div>
    
    </div>
    <div class="show_toggle" >
    <a class="btn hide-on-desktop" id="button-winner-list" style="background:gold;position:fixed;z-index:9999; border:1px solid blue;color:white;user-select: none; ">WINNERS</a>        
    
    <table class="winner_list" >
        <thead>
            <tr>
                <th style="user-select: none; ">
                    TODAY's <i class="fa fa-trophy fa-3x" style="color:black" aria-hidden="true"></i>  WINNER
                    
                </th>
            </tr>
        </thead>
        <tbody>
          
        </tbody>
    </table>
    </div>
    <?php 
        $eventDate = date('Y-m-d',strtotime('2018-12-28'));
        $todayDate= date("Y-m-d");

        if($todayDate==$eventDate){
            echo '<img src="../resources/Merry-Christmas-Text-PNG-Clipart.png" style="z-index:-100;position:fixed;width:45%;height:50%;right:0px;top:25%;"/>'; 
        }
    ?>
    <script>
            // Create new wheel object specifying the parameters at creation time.

           /* function getRandomColor() {
                var letters = '0123456789ABCDEF';
                var color = '#';
                for (var i = 0; i < 6; i++) {
                    color += letters[Math.floor(Math.random() * 16)];
                }
                return color;
            }
*/
            function createWheel(data){
                dataZ=data;
                var qty=data.length;
                var participants=[];
                $.each(data, function(index, obj){

                    participants.push({'fillStyle' : obj.color,'text':obj.memberId});
                });
               
                theWheel = new Winwheel({
                'numSegments'  : qty,     // Specify number of segments.
                'outerRadius'  : 200,   // Set outer radius so wheel fits inside the background.
                'centerX'     : 200,    // correctly position the wheel
                'centerY'     : 200,    // over the background.
                'textFontSize' : 28,    // Set font size as desired.
                'segments'     :        // Define segments including colour and text.

               // [
                    participants,
                //   {'fillStyle' : '#eae56f', 'text' : 'Prize 1'},
                //   {'fillStyle' : '#89f26e', 'text' : 'Prize 2'},
                //   {'fillStyle' : '#7de6ef', 'text' : 'Prize 3'},
                //   {'fillStyle' : '#e7706f', 'text' : 'Prize 4'},
                //   {'fillStyle' : '#eae56f', 'text' : 'Prize 5'},
                 //  {'fillStyle' : '#89f26e', 'text' : 'Prize 6'},
                 //  {'fillStyle' : '#7de6ef', 'text' : 'Prize 7'},
                 //  {'fillStyle' : '#7de6ef', 'text' : 'Prize 8'},
                 //  {'fillStyle' : '#7de6ef', 'text' : 'Prize 9'},
                  // {'fillStyle' : '#e7706f', 'text' : 'Prize 10'}
                //],
                'pins' :  {
            
                    'outerRadius' : 5,
                    'margin'      : 10,
                    'fillStyle'   : 'gold'
                },        
                
                'animation' :           // Specify the animation to use.
                {
                    'type'     : 'spinToStop',
                    'duration' : 10,     // Duration in seconds.
                    'spins'    : 10,     // Number of complete spins.
                    'callbackSound' : playSound,    // Specify function to call when sound is to be triggered
                    'soundTrigger'  : 'pin', // Pins trigger the sound for this animation.
                    'callbackFinished' : alertPrize
                    
                }
            });
            }
            var audio = new Audio('../js/javascript-winwheel-2.7.0/resources/tick.mp3');  // Create audio object and load desired file.
            function playSound()
            {
                // Stop and rewind the sound (stops it if already playing).
                audio.pause();
                audio.currentTime = 0;
        
                // Play the sound.
                audio.play();
            }

            // Vars used by the code in this page to do power controls.
            var wheelPower    = 0;
            var wheelSpinning = false;

            // -------------------------------------------------------
            // Function to handle the onClick on the power buttons.
            // -------------------------------------------------------
            function powerSelected(powerLevel)
            {
                // Ensure that power can't be changed while wheel is spinning.
                if (wheelSpinning == false)
                {
                    // Reset all to grey incase this is not the first time the user has selected the power.
                    document.getElementById('pw1').className = "";
                    document.getElementById('pw2').className = "";
                    document.getElementById('pw3').className = "";

                    // Now light up all cells below-and-including the one selected by changing the class.
                    if (powerLevel >= 1)
                    {
                        document.getElementById('pw1').className = "pw1";
                    }

                    if (powerLevel >= 2)
                    {
                        document.getElementById('pw2').className = "pw2";
                    }

                    if (powerLevel >= 3)
                    {
                        document.getElementById('pw3').className = "pw3";
                    }

                    // Set wheelPower var used when spin button is clicked.
                    wheelPower = powerLevel;

                    // Light up the spin button by changing it's source image and adding a clickable class to it.
                    //document.getElementById('spin_button').src = "spin_on.png";
                  //  document.getElementById('spin_button').className = "clickable";
                }
            }

            // -------------------------------------------------------
            // Click handler for spin button.
            // -------------------------------------------------------
            function startSpin()
            {
                
        
                // Ensure that spinning can't be clicked again while already running.
                if (wheelSpinning == false)
                {
                    // Based on the power level selected adjust the number of spins for the wheel, the more times is has
                    // to rotate with the duration of the animation the quicker the wheel spins.
                    if (wheelPower == 1)
                    {
                        theWheel.animation.spins = 3;
                    }
                    else if (wheelPower == 2)
                    {
                        theWheel.animation.spins = 8;
                    }
                    else if (wheelPower == 3)
                    {
                        theWheel.animation.spins = 15;
                    }

                    // Disable the spin button so can't click again while wheel is spinning.
                   // document.getElementById('spin_button').src       = "spin_off.png";
                  //  document.getElementById('spin_button').className = "";

                    // Begin the spin animation by calling startAnimation on the wheel object.
                    theWheel.startAnimation();
                    
                    // Set to true so that power can't be changed and spin button re-enabled during
                    // the current animation. The user will have to reset before spinning again.
                    wheelSpinning = true;
                }
            }

            // -------------------------------------------------------
            // Function for reset button.
            // -------------------------------------------------------
            function resetWheel()
            {
                theWheel.stopAnimation(false);  // Stop the animation, false as param so does not call callback function.
                theWheel.rotationAngle = 0;     // Re-set the wheel angle to 0 degrees.
                theWheel.draw();                // Call draw to render changes to the wheel.

               // document.getElementById('pw1').className = "";  // Remove all colours from the power level indicators.
               // document.getElementById('pw2').className = "";
              //  document.getElementById('pw3').className = "";

                wheelSpinning = false;          // Reset to false to power buttons and spin can be clicked again.
            }

            // -------------------------------------------------------
            // Called when the spin animation has finished by the callback feature of the wheel because I specified callback in the parameters
            // note the indicated segment is passed in as a parmeter as 99% of the time you will want to know this to inform the user of their prize.
            // -------------------------------------------------------
            function alertPrize(indicatedSegment)
            {
                $.each(dataZ, function(index, obj){
                    
                    if(obj.memberId==indicatedSegment.text){
                        $("#winner_name").text(obj.name);
                        $("#winner_memberId").text(obj.memberId);
                        updateReferalTableWinner(obj.userId);
                        return false; 
                    }
                   
                });
               
                $("#winnerModal").modal();
                wheelSpinning = false;
                // Do basic alert of the segment text. You would probably want to do something more interesting with this information.
              //  alert("You have won " + indicatedSegment.text);
            }
           
        </script>

<div class="modal fade " id="winnerModal" tabindex="-1" role="dialog" aria-labelledby="winnerModalModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered " role="document">
                <div class="modal-content">
                  
                    <div class="modal-body" >
                    
                        <div style="text-align:center"  >
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                           
                            <br/>
                            
                            <i class="fa fa-trophy fa-5x" style="color:gold" aria-hidden="true"></i> 
                            <br/>
                            <h5 id="winner_memberId" class="display-5"><h5>
                            <hr/>
                                <h3 class="display-3" id="winner_name"></h3>    
                            </table>
                        </div>

                    </div>
                   
                </div>
            </div>
        </div>
    

    
    <div class="modal fade " id="referalUserListModal" tabindex="-1" role="dialog" aria-labelledby="referalUserListModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-full" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="referalUserListModalLongTitle">UPDATE USERS REFERAL</h5>
                    
                </div>
                <div class="modal-body">
                    <div class="table-responsive" >
                        <?php
                            echo referalUserListTable();
                        ?>
                    </div>
                </div>
                <div class="modal-footer">
                    <button  type="button" class="btn btn-secondary btn-block" data-dismiss="modal" >
                        CLOSE
                    </button>
                </div>
            </div>
        </div>
    </div>
    
</div>

    
</body>
</html>

**Comment by zarocknz** [comment]
Hi. How many segments are you trying to add? Have you tried reducing the textFontSize? Can you please include a screenshot of your wheel so I can see what is happening? Thanks.

**Comment by hannahhaidi** [comment]
The wheel can be any number. Depends on the user on how many he or she wants to add. 
![wheel](https://user-images.githubusercontent.com/39110679/51240568-ef3ceb00-19b6-11e9-89da-c5300dd4180c.png)

**Comment by zarocknz** [comment]
Thanks for adding the screenshot.

Yes the main issue is that the textFontSize is too large, it needs to be reduced when there are lots of segments. What might also help is aligning the text towards the outside of the wheel to it appears in the fatter part of the segments. This can be done with textAlignment: 'outer'.

Please see this tutorial for details of the text options: http://dougtesting.net/winwheel/docs/tut6_text_alignment

You might also want to set the number of pins based on the data length. Inside the pins config you can specify the **number** as shown in the second example on this page: http://dougtesting.net/winwheel/docs/tut18_displaying_pins
