### ISSUE TITLE
how to set rate of bankrupt?

### ISSUE THREAD

**Issue by cheasamnang** [zarocknz/javascript-winwheel#74]
how to set rate of bankrupt to 1% or 0,1% ?

**Comment by zarocknz** [comment]
I suggest you do some reading on Math and probability as you will need to write your own function to determine how often certain things happen. You can set the result of the wheel before the spin happens so its not completely random - please see this tutorial: http://dougtesting.net/winwheel/docs/tut14_setting_the_prize
