### ISSUE TITLE
Possibility to spin the wheel via drag and drop

### ISSUE THREAD

**Issue by sirzento** [zarocknz/javascript-winwheel#80]
Is it possible to spin the wheel via drag and drop? if no, would it be easy to implement it?

**Comment by zarocknz** [comment]
Drag and drop? You don't mean touch - i.e. pull wheel down with finger then release to spin?

Either way there are no built in options for these. I would think its not too difficult to implement this as you can add any javascript events you like to the canvas then use event handlers for these to alter the wheel including starting the spinning.
