### ISSUE TITLE
How to use gradient colour on fillStyle for segments.

### ISSUE THREAD

**Issue by MarioMoraSRT** [zarocknz/javascript-winwheel#82]
Hi,
This is Mario. Just to ask about how to use gradients on fillStyle (segments).
In tuto#7: http://dougtesting.net/winwheel/docs/tut7_colours_lines_fonts
You mentioned it is possible to use gradients to set the color to a segment, but, there is no any sample how-to and I don't know how is called the attribute or method to use it.

Also refer.
http://dougtesting.net/winwheel/refs/class_segment

Does any solution available for this? How to implement the gradient color.

I searched here on your github page also on stackoverflow using Winwheel topic but nothing... 
Thanks in advance for your help, 

Regards.
Mario Mora.

**Comment by zarocknz** [comment]
Hi Mario,

Thanks for getting in touch. Yes I avoided talking about gradients as they don't quite work as you might expect and may require a bit of work to get as desired. Perhaps I should finally add a section to the tutorials this holidays showing how to use them.

The Winwheel.js code utilizes a lot of HTML canvas features and the fillStyle is one of them. This means you can use any of the the standard HTML canvas options for the fillStyle such as solid colours, colours with transparency (alpha), and gradients.

Here is an example of how to do the easiest type of gradient - a radial gradient - with the Winwheel. I modified the basic code wheel example...

```javascript
// First get the context of the canvas as the gradient is created on this.
let canvas = document.getElementById('canvas');
let ctx = canvas.getContext('2d');

// Create radial gradient (this works best with the roundness of the wheel)
// https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createRadialGradient
// Many values should be the centre of the canvas. If the canvas is square can just use the height / 2.
// The remaining values are the radius of the starting circle then the radius of the ending circle.
let canvasCenter = canvas.height / 2;

// x0,y0,r0,x1,y1,r1
let radGradient = ctx.createRadialGradient(canvasCenter, canvasCenter, 50, canvasCenter, canvasCenter, 250);

// Add the colour stops - 0.0 should be the first, 1.0 the last, others in between.
radGradient.addColorStop(0, "red");
radGradient.addColorStop(0.5, "white");
radGradient.addColorStop(1, "aqua");

// Create new wheel object specifying the parameters at creation time.
let theWheel = new Winwheel({
    'numSegments'  : 8,           // Specify number of segments.
    'outerRadius'  : 212,         // Set outer radius so wheel fits inside the background.
    'textFontSize' : 28,          // Set font size as desired.
    'fillStyle'    : radGradient, // Can set the fillstyle globally.
    'segments'     :              // Define segments including colour and text.
    [
       {'text' : 'Prize 1'},
       {'text' : 'Prize 2'},
       {'text' : 'Prize 3'},
       {'text' : 'Prize 4'},
       {'text' : 'Prize 5'},
       {'text' : 'Prize 6'},
       {'text' : 'Prize 7'},
       {'text' : 'Prize 8'}
    ],
    'animation' :           // Specify the animation to use.
    {
        'type'     : 'spinToStop',
        'duration' : 5,     // Duration in seconds.
        'spins'    : 8,     // Number of complete spins.
        'callbackFinished' : alertPrize
    }
});
```
As you can see above, the steps are...
* Get the canvas
* Get canvas context
* Create gradient setting X and Ys and the radiuses
* Add colour stops
* Set the fillStyle to the gradient

If you would like to know more I would suggest looking online for tutorials about HTML canvas createRadialGradient and createLinearGradient. A place to start could be the mozilla developer docs https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createRadialGradient

Hope this helps.

**Comment by zarocknz** [comment]
One other thing, if you would like different segments to have a different coloured gradient then create more than one radialGradient - for example radGradientRed, radGradientGreen, radGradientBlue - and then assign the gradient to the fillStyle of each segment like this...

```javascript
let theWheel = new Winwheel({
    'numSegments'  : 9,      // Specify number of segments.
    'outerRadius'  : 212,    // Set outer radius so wheel fits inside the background.
    'textFontSize' : 28,     // Set font size as desired.
    'segments'     :         // Define segments including colour and text.
    [
       {'fillStyle' : radGradientBlue, 'text' : 'Prize 1'},
       {'fillStyle' : radGradientRed, 'text' : 'Prize 2'},
       {'fillStyle' : radGradientGreen, 'text' : 'Prize 3'},
       {'fillStyle' : radGradientBlue, 'text' : 'Prize 4'},
       {'fillStyle' : radGradientRed, 'text' : 'Prize 5'},
       {'fillStyle' : radGradientGreen, 'text' : 'Prize 6'},
       {'fillStyle' : radGradientBlue, 'text' : 'Prize 7'},
       {'fillStyle' : radGradientRed, 'text' : 'Prize 8'},
       {'fillStyle' : radGradientGreen, 'text' : 'Prize 9'}
    ],
});
```
