### ISSUE TITLE
Add probability to the Code and only stop on the segment based on the percentage

### ISSUE THREAD

**Issue by Anthony-david** [zarocknz/javascript-winwheel#83]
Actually i am looking to add probability to the section based on the percentage.... Let me know if anyone can help I am ready to pay for it... Email-- anthonyuidesigner@gmail.com Phone/whatsapp: +91 7400169004

**Comment by zarocknz** [comment]
Please be sure to read this tutorial on how to specify the winning prize before the spinning happens http://dougtesting.net/winwheel/docs/tut14_setting_the_prize

What you use to work out the probability is up to you - could be a simple as picking a random number between 0 and 360 and then using this to set theWheel.animation.stopAngle to this as shown in the tutorial.

I suggest consulting Dr Google if you would like more info on percentages and probability.
