### ISSUE TITLE
Prevent text from going on new line

### ISSUE THREAD

**Issue by damianobarbati** [zarocknz/javascript-winwheel#88]
Is there a way to prevent text breaking and force text on same line?

I'm trying to draw a simple roulette but every number is broke on two lines (i.e: 20 => 2 on 1st line, 0 2nd line).
I'm using `textOrientation: "vertical"`.

BTW: great work man!

**Comment by zarocknz** [comment]
Hi, thanks for getting in touch.

Sounds like the textOrientation property might be vertical, try setting it to curved and perhaps adjusting the textAlignment and margin to sit the text near the outside of the wheel.

There is a detailed tutorial about the text orientation and alignment options here http://dougtesting.net/winwheel/docs/tut6_text_alignment

Cheers.
