### ISSUE TITLE
Can i change Font Family or Font Size by CSS or Any Script?

### ISSUE THREAD

**Issue by Anthony-david** [zarocknz/javascript-winwheel#91]
Hi,

I am looking to change the Font family of the Text inside the Wheel. So is there any option to Change canvas with script or css?

**Comment by zarocknz** [comment]
Hi,

You cannot use CSS to style canvas elements. Drawing on canvas is like drawing in MS paint. You can only use basic lines, shapes, colours, and text.

Yes it is possible to change the font family, text colour etc in Winwheel.js. Please see this tutorial which discusses the options: http://dougtesting.net/winwheel/docs/tut7_colours_lines_fonts

Regards,
DouG.
