### ISSUE TITLE
Stop wheel on particular (setted) segment

### ISSUE THREAD

**Issue by MaliugaSergiy** [zarocknz/javascript-winwheel#93]
Is it possible to set particular segment to stop wheel?
I wont to stop wheel on setted segment? not randome.

**Comment by zarocknz** [comment]
Yes. Please read this tutorial http://dougtesting.net/winwheel/docs/tut14_setting_the_prize

**Comment by MaliugaSergiy** [comment]
@zarocknz thanks a lot!
